CAT_COLUMNS = ['article_type', 'year', 'language', 'OECD', 'first_OECD']
NUMERIC_COLUMNS = ['eLIBRARY ID', 'year', 'Цитирования']

COLUMNS_RENAME = {
    'eLIBRARY ID': 'ID',
    'title_en': 'title',
    'abstract_en': 'abstract',
    'key_words_en': 'keywords'
}

FIRST_LEVEL = {'Natural Sciences':['Mathematics', 'Computer and information sciences', 'Physical sciences and astronomy', 'Chemical sciences', 'Earth and related environmental sciences', 'Biological sciences', 'Other natural sciences'],
                 'Engineering and Technology':['Civil engineering', 'Electrical engineering, electronic engineering', 'Mechanical engineering', 'Chemical engineering', 'Materials engineering', 'Medical engineering', 'Environmental engineering', 'Environmental biotechnology', 'Industrial biotechnology', 'Nano-technology', 'Other engineering and technologies'],
                 'Medical and Health Sciences': ['Basic medical research', 'Clinical medicine', 'Health sciences', 'Other medical sciences'],
                 'Agricultural Sciences': ['Agriculture, forestry, fisheries', 'Animal and dairy science', 'Veterinary science', 'Other agricultural sciences'],
                 'Social Sciences': ['Psychology', 'Economics and business', 'Educational sciences', 'Sociology', 'Law', 'Political science', 'Social and economic geography', 'Media and communication', 'Other social sciences'],
                 'Humanities': ['History and archaeology', 'Languages and literature', 'Philosophy, ethics and religion', 'Art', 'Other humanities']}

TRANSLATION_DICT = {'Natural Sciences':'Естественные науки и точные науки',
                    'Mathematics':'Математика',
                    'Computer and information sciences':'Компьютерные и информационные науки',
                    'Physical sciences and astronomy':'Физика и астрономия',
                    'Chemical sciences':'Химические науки',
                    'Earth and related environmental sciences':'Науки о Земле и окружающей среде',
                    'Biological sciences':'Биологические науки',
                    'Other natural sciences':'Прочие естественные науки',
                    'Engineering and Technology':'Инженерные науки и технологии',
                    'Civil engineering':'Строительство и архитектура',
                    'Electrical engineering, electronic engineering':'Электротехника и электроника',
                    'Mechanical engineering':'Машиностроение',
                    'Chemical engineering':'Химическая инженерия',
                    'Materials engineering':'Технологии материалов',
                    'Medical engineering':'Медицинские технологии',
                    'Environmental engineering':'Энергетика и рациональное природопользование',
                    'Environmental biotechnology':'Экологические биотехнологии',
                    'Industrial biotechnology':'Промышленные биотехнологии',
                    'Nano-technology':'Нанотехнологии',
                    'Other engineering and technologies':'Прочие технологии',
                    'Medical and Health Sciences':'Медицинские и общественное здравоохранение',
                    'Basic medical research':'Фундаментальные медицина',
                    'Clinical medicine':'Клиническая медицина',
                    'Health sciences':'Науки о здоровье',
                    'Other medical sciences':'Прочие медицинские науки',
                    'Agricultural Sciences':'Сельскохозяйственные науки',
                    'Agriculture, forestry, fisheries':'Сельское хозяйство, лесное хозяйство, рыбное хозяйство',
                    'Animal and dairy science':'Животноводство и молочное дело',
                    'Veterinary science':'Ветеринарные и',
                    'Other agricultural sciences':'Прочие сельскохозяйственные науки',
                    'Social Sciences':'Социальные науки',
                    'Psychology':'Психология',
                    'Economics and business':'Экономика и бизнес',
                    'Educational sciences':'Науки об образовании',
                    'Sociology':'Социология',
                    'Law':'Право',
                    'Political science':'Политология',
                    'Social and economic geography':'Социальная и экономическая география',
                    'Media and communication':'СМИ и массовые коммуникации',
                    'Other social sciences':'Прочие социальные науки',
                    'Humanities':'Гуманитарные науки',
                    'History and archaeology':'История и археология',
                    'Languages and literature':'Языки и литература',
                    'Philosophy, ethics and religion':'Философия, этика и религиоведение',
                    'Art':'Искусствоведение',
                    'Other humanities':'Прочие гуманитарные науки'}
